services:
  - type: web
    name: aiservice
    env: docker
    plan: free
    branch: main
    repo: https://github.com/whatfor2000/ecs-production-ai-service # Update this
    rootDir: ecs-production-ai-service
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
